title: Healthy
slogan: Health check endpoints for WordPress
description: Add reliable health check endpoints to WordPress with Healthy. Perfect for uptime monitoring, automated infrastructure checks and Kubernetes readiness.

domain: healthy.vincentbitter.nl
url: https://healthy.vincentbitter.nl
baseurl: 

sass:
  style: compressed
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/news/p/page:num/"
permalink: /news/:year/:slug/